### ISSUE TITLE
Questions, rather than issue

### ISSUE THREAD

**Issue by theangryangel** [xoe-labs/dodoo-loader#1]
Forgive the question (if github issues is not the place I understand), but I was led here from looking at the odoo_csv_import repo. This project (and odoo_csv_import) both look quite similar to something I've started working on earlier today, and I'm wondering if I even need to continue or if I can somehow be useful enough to contribute.

I'm looking at the chunking code (I'm unfamiliar with pandas) and trying to figure if the way it's done currently it would end up splitting line information across multiple files? For example, when importing via the GUI I know I need to blank certain fields otherwise odoo does not consider them to be lines. Is that also the case via the API? Or am I completely barking up the wrong tree?

**Comment by blaggacao** [comment]
There is no such thing as a wrong place for the right questions ;-)

>It would end up splitting line information across multiple files

No, it works on dataframe rows grouping them by a on-the-fly created array which happens to contain be n=chunksize repetitions of every number. 

Then the loader takes those chunks and loads them, each chunk in a separate request. This is useful if some validations are too heavy for the request timeout when a certain chuck size is exceeded. V12 has greatly improved efficiency, but in some situations chunks still might be useful.

It currently does not work with nested lines (2many on separate lines). This use case is obviated, though, through the dependency graph detection. It is trivial to out-factor nested data into it's own file with the added benefit of addressability through external IDs.

I don't understand the question about the blank fields in the UI. Could you elaborate?

Just as a sidenote: dodoo-loader does not split files, all data is read into panda dataframe and subsequent transformations are done (efficiently) in memory before loading.

**Comment by theangryangel** [comment]
Thank you for the kind words :) I appreciate it. I know different people run repos in different ways and dont like "support" questions (and mine are definitely in that category as I'm starting to get to grips with the innards of Odoo atm) 

> I don't understand the question about the blank fields in the UI. Could you elaborate?

So far I've been relying on the GUI importer built in, so given an example of an invoice "header" with 2 lines on the same file the GUI seems to expect that the invoice "header" fields get blanked out on the 2 lines, in order to import..

However that said I now realise (with your previous comment) that I should instead of doing this import the header, set the external id, and then in a second stage import the lines, referencing the external id of the header? Given I've been doing that for customers, suppliers, etc. I don't know why this didn't dawn on me :fearful:

**Comment by blaggacao** [comment]
> blanked out on the 2 lines, in order to import

I somehow felt it was something about nested imports. It's definitely not yet possible with this tool, as I spare the somewhat obscure flattening mechanism of Odoo, and especially if you need to do repeated loads (because of an iterative approach), not having external ides does not help at all. Therefore, I consider nested imports bad and probably won't support them.

About "second stage": you can just define multiple import files, dodoo-loader will figure out the dependency graph ("right loading order") for you automatically. It will also sort your lines so that ona a hierarchy table (eg product categories), they will always load in the right order.

**Comment by blaggacao** [comment]
Your welcome ;-)

**Comment by theangryangel** [comment]
Just wanted to say first off, thank you @blaggacao. I've found the time to test this today and its working beautifully once I got it installed.

The hopefully final question I've got is actually around getting dodoo-loader installed. `pip3 install dodoo-loader` kinda got me stuck in a loop. As I'm not still hugely involved in the python environment I kinda got a bit stuck where it complains it needs >=2.0.0.rc2, but can only find those versions available on pypy.

Now I see you've referenced a fork in dependency_links, but I don't see to have a way of getting pip to look at that? I did get dodoo-loader installed by what is probably a crook method (clone repo of dodoo-loader, edit setup.py to remove the requirement, install, then install your forked version of click-odoo on top - which all feels very wrong). Am i being thick? 

Sorry, I hate asking questions like this, and I feel quite useless.

**Comment by blaggacao** [comment]
Can you try `pip install -e` ? See: https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

Other than that: this project, while being able to run stand alone was crafted to run as integrated part of the devops tooling of the [dockery odoo project](https://xoe-labs.github.io/dockery-odoo/).

**Comment by theangryangel** [comment]
`pip install -e` yields the following;

```
DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release. A possible replacement is PEP 508 URL dependencies. You can find discussion regarding this at https://github.com/pypa/pip/issues/4187.
Collecting click-odoo>=2.0.0.rc2 (from dodoo-loader==0.5.1)
  Could not find a version that satisfies the requirement click-odoo>=2.0.0.rc2 (from dodoo-loader==0.5.1) (from versions: 1.0.0a1, 1.0.0a2, 1.0.0b1, 1.0.0b2, 1.0.0b3, 1.0.0b4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.2.0, 1.3.0)
No matching distribution found for click-odoo>=2.0.0.rc2 (from dodoo-loader==0.5.1)
```

`pip 18.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)`.

I can get it installed by first grabbing the relevant repo and installing it, so;
`git clone https://github.com/xoe-labs/click-odoo.git && cd click-odoo && git checkout 2.0.0 && pip3 install -e`

**Comment by blaggacao** [comment]
Thanks! That seems something to put on my todo list!
