### ISSUE TITLE
Large quantities of data

### ISSUE THREAD

**Issue by theangryangel** [xoe-labs/dodoo-loader#2]
Hi, me again. Sorry.

The company work for has consultancy time with Odoo. Their recommendation for imports is via the GUI. That just doesnt work for us at the moment purely because of the quantity of data I'm feeding in during a test migration.

With that explanation out of the way...

I've got about 315k partners (suppliers, customers (mostly shipping addresses), etc.). I used dodoo-loader to get a lot of this data in. Worked mostly fine. 

Unfortunately since getting all this data in subsequent imports seem to fail in a way I dont fully understand.

Importing small quantities (< 5 or so records) is fine. More than that and dodoo-loader logs that its gotten IDs back, but there's nothing in the database. For example;

```
},{
    "batch": 104,
    "candidates": [
        "__testimport.order_879069"
    ],
    "loaded": [
        109
    ],
    "model": "sale.order",
    "state": "success",
    "x_msgs": []
},{
```

```
user@test:~$ sudo -u postgres psql redacted -c "select count(*) from sale_order"
 count 
-------
     0
(1 row)
```

I'm definitely looking at the right DB, I can see the postgres seq has advanced, so I'm assuming its rolled back. But I see nothing of value in the `odoo-server.log` at the moment I'm struggling to understand why Odoo would respond with an ID in the middle of a transaction, if it can roll it back?

I can't really use our Odoo consultancy time since dodoo-loader is an unsupported tool, and I'll be (quite reasonably) asked to load all that data in by hand to ensure it's not an import problem.. But it will literally take days. 

Any suggestions before I start seriously considering doing that?

**Comment by blaggacao** [comment]
@theangryangel Hi Karl, No worries I'm glad to help. We've been loading 120k of SO + Invoices + 360k Inventory moves still with our internal predecessor tool on V10 those days. Full loading and all validations takes 150 full hours to finish. So, I guess, we're familiar with those kind of workloads.

If it's an option for you I'd love to professionally lend you a hand in this project and provide you with all the support needed to make the loading a success.

Would you drop me a quick line to dar@xoe.solutions ? I think we can arrange something, quickly.
